# Add or edit sources freely (agency/url/base)
# Keep list concise; your workflow is scheduled daily.
- agency: DST (Department of Science & Technology)
  url: https://dst.gov.in/call-for-proposals
  base: https://dst.gov.in
- agency: DBT (Department of Biotechnology)
  url: https://dbtindia.gov.in/latest-announcements
  base: https://dbtindia.gov.in
- agency: ICMR (Indian Council of Medical Research)
  url: https://main.icmr.nic.in/calls
  base: https://main.icmr.nic.in
- agency: IGSTC (Indo-German Science & Technology Centre)
  url: https://www.igstc.org/
  base: https://www.igstc.org
- agency: SERB (Science and Engineering Research Board)
  url: https://www.serbonline.in/SERB/HomePage
  base: https://www.serbonline.in
- agency: UGC (University Grants Commission)
  url: https://www.ugc.ac.in/
  base: https://www.ugc.ac.in
- agency: European Research Council
  url: https://erc.europa.eu/news-events/news
  base: https://erc.europa.eu
- agency: Wellcome Trust (UK)
  url: https://wellcome.org/grant-funding/schemes
  base: https://wellcome.org
