name: Update data.json (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"   # 03:15 UTC daily

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          # Optional Playwright browser (only used if sources.yaml enables render: playwright)
          python - <<'PY'
import subprocess
try:
    subprocess.check_call(["playwright", "install", "--with-deps", "chromium"])
except Exception as e:
    print("Playwright install skipped:", e)
PY

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # optional
        run: |
          python scraper/agent.py

      - name: Commit & push data.json if changed
        run: |
          if [[ -n "$(git status --porcelain data.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data.json
            git commit -m "chore: auto-update data.json ($(date -u +'%Y-%m-%d %H:%M UTC'))"
            git push
          else
            echo "No changes to commit"
          fi
