name: update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 2 * * *"   # daily at ~02:17 UTC (staggered)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # optional (not used in this version)
        run: |
          python -m scraper.agent

      - name: Commit & push data.json
        run: |
          git config user.name  "actions-user"
          git config user.email "actions@users.noreply.github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update data.json ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi
