name: Update data.json (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC daily

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
      - name: Run scraper
        run: python scraper/scraper.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain data.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data.json
            git commit -m "chore: auto-update data.json ($(date -u +'%Y-%m-%d %H:%M UTC'))"
            git push
          else
            echo "No changes in data.json"
          fi
