name: Update data.json (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "12 3 * * *"   # 03:12 UTC daily (change as you wish)

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # optional
        run: |
          python scraper/scraper.py

      - name: Commit & push data.json
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update data.json ($(date -u +'%Y-%m-%d %H:%M:%SZ'))"
            git push
          fi
